#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>
#include <sys/socket.h>
#include <netinet/in.h>


int main(int argc, char **argv)  
{

	openlog("MyMsgMARK", LOG_CONS | LOG_PID, LOG_SYSLOG);  
	//openlog("MyMsgMARK", LOG_PID, LOG_MAIL);  
	syslog(LOG_EMERG,  
			"This is a syslog test message generated by program '%s'/n",  
			argv[0]);  
	closelog();  
	return 0;  

} 

